on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

name: cli-build-2

permissions: write-all

jobs:
  R-CMD-check:
    runs-on: windows-11-arm

    name: windows-11-arm

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      
      - name: Clone cli repo
        run: |
          "Here 1"
          # Install R 4.5.1
          $url = "https://cran.r-project.org/bin/windows/base/R-4.5.1-win.exe"
          Invoke-WebRequest -Uri "$url" -OutFile R-x86_64.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath R-x86_64.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait

          "Here 2"
          # Install Rtools45 AARCH64
          $url = "https://cran.r-project.org/bin/windows/Rtools/rtools45/files/rtools45-aarch64-6608-6492.exe"
          Invoke-WebRequest -Uri "$url" -OutFile rtools45.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath rtools45.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES /DIR='C:\rtools45'" -NoNewWindow -Wait
          "RTools45 installed"
          
          "Here 3"
          # Add R and Rtool45 binaries to PATH
          $ENV:PATH = "C:\Program Files (x86)\R\R-4.5.1\bin\x64;C:\rtools45\usr\bin;$ENV:PATH"

          git clone --depth 1 --branch v3.6.5 https://github.com/r-lib/cli.git
          cd cli

          # Install devtools
          $rscript = "Rscript"
          $args = "-e", "install.packages('devtools', repos = 'https://cloud.r-project.org/', type = 'binary')"
          & $rscript $args
          
          # Run devtools load_all()
          $args = "-e", "devtools::load_all('./')"
          & $rscript $args
