on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

name: win-11-arm-quarto-test-r-x86

permissions: write-all

jobs:
  R-CMD-check:
    runs-on: windows-11-arm

    name: windows-11-arm

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      
      - name: Render Quarto doc using pre-installed x86_64 R 4.4.2
        run: |
          $Env:Path -split ";"
          # Get-ChildItem -Path "C:\" -Name
          # Get-ChildItem -Path "C:\Program Files (x86)\" -Name
          # Get-ChildItem -Path "C:\Program Files (x86)\R\" -Name
          # Get-ChildItem -Path "C:\rtools45\" -Name
          Remove-Item -Path "C:\rtools45\" -Recurse -Force
          # Install x86_64 RTools44
          # $url = "https://cran.r-project.org/bin/windows/Rtools/rtools44/files/rtools44-6459-6401.exe"
          # Invoke-WebRequest -Uri "$url" -OutFile rtools44.exe -UseBasicParsing -UserAgent "NativeHost"
          # Start-Process -FilePath rtools44.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          
          # Add Rtool44 binaries to PATH
          # $ENV:PATH = "C:\rtools44\usr\bin;$ENV:PATH"
          
          # Install pandoc
          choco install pandoc --no-progress
          refreshenv

          # Install Quarto
          choco install quarto --no-progress
          refreshenv

          # Install TinyTeX
          $rscript = "Rscript"
          # $args = "-e", "install.packages(c('tinytex'), repos = 'https://cloud.r-project.org/'); tinytex::install_tinytex(); tinytex::tlmgr_install(c('makeindex', 'upquote', 'inconsolata'))"
          # & $rscript $args

          # Add TinyTeX binaries to PATH
          # $ENV:PATH = "C:\Users\runneradmin\AppData\Roaming\TinyTeX\bin\windows;$ENV:PATH"
          
          # Install knitr and rmarkdown
          $args = "-e", "install.packages(c('knitr', 'rmarkdown'), repos = 'https://cloud.r-project.org/');"
          & $rscript $args
          
          # Render the rmarkdown document
          $args = "-e", "rmarkdown::render('index-rmd.Rmd', output_file = 'index-rmd-r-x86.html')"
          & $rscript $args

          git config user.name "Tom Palmer"
          git config user.email "remlapmot@hotmail.com"
          git add index-rmd-r-x86.html
          git commit -m "Update index-rmd-r-x86.html"
          git push

      - name: Render the Quarto document
        run: |
          quarto --version
          quarto check knitr --log-level debug
          quarto render index.qmd --output index-r-x86.html

          # Commit and push
          git config user.name "Tom Palmer"
          git config user.email "remlapmot@hotmail.com"
          git add index-r-x86.html
          git commit -m "Update index-r-x86.html"
          git push
